config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "dashboard#index"
  get "up" => "rails/health#show", as: :rails_health_check
  
  get  "/reconciliation", to: "reconciliations#index"

  resources :arrear_cases do
    collection do
      get  :imports
      post :imports
      get  :export
      get  :sample_template
      delete :bulk_destroy
      delete :destroy_all 
      
    end
  end

  resources :tax_payments, only: [:index] do
    collection do
      get  :imports
      post :imports
      get  :sample_template
      get  :export_matched
      get  :export
    end
  end

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtoArrears</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <% if user_signed_in? %>
      <nav class="bg-gray-800 text-white p-3 flex justify-between items-center fixed w-full top-0 z-50">
        <div class="flex items-center gap-6">
          <%= link_to "ARTO Arrear Desk", root_path, class: "font-semibold hover:underline" %>
          <%= link_to "Home", root_path, class: "hover:underline" %>
          <%= link_to "Notices", arrear_cases_path, class: "hover:underline" %>
          <%= link_to "Tax Payments", tax_payments_path, class: "hover:underline" %>
		  <%= link_to "Reconciliation",
		                reconciliation_path,
		                class: "hover:underline" %>
        </div>
        <div class="flex items-center">
          <span class="mr-4">Signed in as <%= current_user.email %></span>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-600 px-3 py-1 rounded" %>
        </div>
      </nav>
    <% end %>

    <main class="container mx-auto mt-20 px-5">
      <%= yield %>
    </main>
  </body>
</html>